version: "3"
services:
  db:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: php
        # MYSQL_USER: root
        MYSQL_USER: user
        MYSQL_PASSWORD: hoge
        MYSQL_ROOT_PASSWORD: password
    ports:
        - 33060:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql:/var/lib/mysql

  php:
    build: ./php
    volumes:
      - ./php/src:/usr/share/php/src
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["db"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/src:/usr/share/php/src
    restart: always
    ports: ["80:80"]
    depends_on: ["php"]
