version: "3"
services:
  db:
    build: ./mysql
    ports:
        - 33060:3306
    volumes:
      - db-store:/var/lib/mysql

  php:
    build: ./php
    volumes:
      - ./src:/usr/share/src
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["db"]

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/src
    restart: always
    depends_on: ["php"]

volumes:
  db-store:
